name: Build Autonity ABIs and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone Autonity Repository
        run: git clone https://github.com/autonity/autonity.git

      - name: Checkout Tag v1.1.2
        working-directory: ./autonity
        run: git checkout tags/v1.1.2 -b vv1.1.2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Go mod tidy
        working-directory: ./autonity
        run: go mod tidy

      - name: Build contracts
        working-directory: ./autonity
        run: make contracts

      - name: Prepare ABI JSON files
        run: |
          # Buat direktori baru untuk menampung file JSON
          mkdir -p ./abi-json

          # Salin file .abi dari hasil build dan ubah ekstensinya menjadi .json
          echo "Copying and renaming ABI files to JSON..."
          for file in ./autonity/params/generated/*.abi; do
            if [ -f "$file" ]; then
              base_name=$(basename "$file" .abi)
              cp "$file" "./abi-json/${base_name}.json"
            fi
          done
          
          echo "Generated JSON files:"
          ls -lah ./abi-json

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload direktori abi-json
          path: ./abi-json

  deploy:
    # Job ini bergantung pada keberhasilan job 'build'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Step 1: Checkout repository (diperlukan oleh action directory-listing)
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@main
        with:
          FOLDER: .

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
