name: Build Autonity ABIs and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      
      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Build and Prepare ABI files
        run: make

      - name: Upload ABI files for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: abi-files
          path: ./autonity-abi   

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download ABI files
        uses: actions/download-artifact@v4
        with:
          name: abi-files

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@main
        with:
          FOLDER: .

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
